# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - "./requirements.sh"
  - "pip install -e ."
  - "pip install https://github.com/brandon-rhodes/assay/archive/master.zip"

script:
  - "pip install unittest2"
  - "assay --batch skyfield.tests"
  - "make -C skyfield/documentation doctest"
